### PR TITLE
Support non-Swift projects

### PR DESCRIPTION
**Pull request by RishatShamsutdinov**
* Add support for non-Swift projects
* Add support of usage in Objective-C++ files

### CODE REVIEW

**Comment by RishatShamsutdinov** [comment]
Can you please publish this version to CocoaPods?

`git tag '2.2.1' && git push origin master --tags && pod trunk push`

**Comment by NSProgrammer** [comment]
I'm afraid this does not pass the linter:

```
]$ pod spec lint
ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.

 -> TwitterLoggingService (2.2.1)
    - ERROR | [iOS] public_header_files: The pattern includes header files that are not listed in source_files (/private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSConsoleOutputStreams.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSCrashlyticsOutputStream.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSDeclarations.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSFileOutputStream+Protected.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSFileOutputStream.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSLog.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSLoggingService+Advanced.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSLoggingService.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSProtocols.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLSRollingFileOutputStream.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TLS_Project.h, /private/var/folders/pr/vbg8jt410nx78mksm3f7bxqh0000gp/T/CocoaPods/Lint/Pods/TwitterLoggingService/Classes/TwitterLoggingService.h).

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```


I don't really have the cycles to fix this, so I might have to revert this PR if it can't be figured out before any future PRs to the project.

**Comment by RishatShamsutdinov** [comment]
`pod spec lint --allow-warnings

 -> TwitterLoggingService (2.2.1)
    - WARN  | source: Git sources should specify a tag.

Analyzed 1 podspec.

TwitterLoggingService.podspec passed validation.`

I changed git repository to my ([https://github.com/RishatShamsutdinov/ios-twitter-logging-service.git](url)) & it works fine.

**Comment by RishatShamsutdinov** [comment]
Validation of original repository:
```
~/Projects/ios-twitter-logging-service-original ▸ master ▸ git pull
Already up-to-date.
~/Projects/ios-twitter-logging-service-original ▸ master ▸ pod spec lint

 -> TwitterLoggingService (2.2.1)

Analyzed 1 podspec.

TwitterLoggingService.podspec passed validation.
```

**Comment by RishatShamsutdinov** [comment]
Just reproduced this issue on CocoaPods `1.0.1. #5 fixes it.

**Pull request merged**
